[package]
name = "genshin-skip-conversation"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.58", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_Graphics_Gdi", "Win32_Storage_Xps", "Win32_UI_HiDpi", "Win32_System_SystemServices"] }
rdev = "0.5.3"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0.102"
opencv = "0.98.2"
