name: CI

on:
  push:
    branches:
      - rust
  pull_request:
    branches:
      - rust
  workflow_dispatch:

jobs:
  lint-and-format-check:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: cargo check
        if: always()
        run: cargo check --all-targets

      - name: cargo fmt
        if: always()
        run: cargo fmt --all --check

      - name: cargo clippy
        if: always()
        run: cargo clippy --all-targets -- -D warnings

      - name: cargo test
        if: always()
        run: cargo test
