name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build in Release Mode
        run: cargo build --release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            target/release/genshin-skip-conversation.exe
          generate_release_notes: true
